config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  get "/play", to: "games#show"
  resources :games, only: [:create] do
    resources :actions, only: [:index, :create]
  end
  get 'pages/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :game
  validates :parameters, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  before_create :generate_unique_code

  enum status: {
    lobby: 0,
    playing: 1,
    completed: 2,
  }

  def add_player(name, metadata: {})
    player = Player.new(Random.uuid, name, metadata)
    players = (initial_state['players'] || []) << player.to_h
    update(initial_state: initial_state.merge('players' => players))
  end

  def remove_player(id)
    players = (initial_state['players'] || []).reject { |player| player[:id] == id }
    update(initial_state: initial_state.merge('players' => players))
  end

  private

  def generate_unique_code
    self.code = loop do
      random_code = SecureRandom.hex(3).upcase # Generates a 6-character hex string
      break random_code unless Game.exists?(code: random_code)
    end
  end
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  before_action :set_game

  def create
    @action = @game.actions.new(action_params)
    if @action.save
      render json: @action, status: :created
    else
      render json: @action.errors, status: :unprocessable_entity
    end

  end

  def index
  end

  private
    def set_game
      @game = Game.find(params[:id])
    end

    def action_params
      params.require(:action).permit(:parameters)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  PROFILE_PICTURES = Dir[Rails.root.join("public", "images", "love_letter", "characters", "*.webp")].map { |f| File.basename(f) }
  def create
    game = Game.create
    redirect_to play_url(code: game.code, name: params[:name])
  end

  def start
  end

  def show
    @game = Game.find_by_code(params[:code])
    if @game.nil?
      redirect_to root_path, alert: "No game found with code #{params[:code]}"
    end
    @cards = [
      Cards::Baron.new(nil, nil),
      Cards::Princess.new(nil, nil),
    ] # Two Cards
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/actions/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Actions#create</h1>
  <p>Find me in app/views/actions/create.html.erb</p>
</div>

app/views/actions/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Actions#index</h1>
  <p>Find me in app/views/actions/index.html.erb</p>
</div>

app/views/games/_lobby.html.erb
<h1>Lobby</h1>
<div class="flex flex-row">
<% GamesController::PROFILE_PICTURES.each do |profile_url| %>
  <a class="cursor-pointer">
    <img class="rounded mr-4 w-[100px]" src=<%= "/images/love_letter/characters/#{profile_url}" %> />
  </a>
<% end %>
</div>
<div id="name-form">
  <input id="name-input" type="text" placeholder="Enter your name" />
  <button id="enter-lobby">Enter Lobby</button>
</div>
<div id="lobby" style="display: none;">
  <input type="hidden" id="game-code" value="<%= @game.code %>" />
  <h2>Users in the lobby:</h2>
  <div id="user-list"></div>
</div>

app/views/games/_playing.html.erb
<div class="container mt-14 mx-auto flex flex-col">
  <div class="flex flex-row space-x-4">
    <% GamesController::PROFILE_PICTURES[0..3].each do |profile_picture| %>
      <%= render "love_letter/player", player: Player.new(nil, "name", metadata: {profile_picture: profile_picture}) %>
    <% end %>
  </div>
  <div class="my-4">Deck</div>
  <div class="my-4">Your hand</div>
  <div class="flex flex-row space-x-8">
    <% @cards.each do |card| %>
      <%= render "love_letter/card", card: %>
    <% end %>
  </div>
</div>

app/views/games/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Games#create</h1>
  <p>Find me in app/views/games/create.html.erb</p>
</div>

app/views/games/show.html.erb
<div>
  <% if @game.lobby? %>
    <%= render "games/lobby", game: @game %>
  <% elsif @game.playing? %>
    <%= render "games/playing", game: @game %>
  <% elsif @game.completed? %>
    <%= render "games/completed", game: @game %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoveLetterOnline</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= render "shared/flash" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/love_letter/_card.html.erb
<div class="group cursor-pointer h-full card rounded-xl shadow-lg bordered max-w-[300px] bg-neutral text-white mb-5">
  <div class="relative opacity-80 transition duration-300 ease-in-out group-hover:opacity-100 overflow-hidden rounded-t-xl">
    <div class="z-10 absolute top-0 left-0 mr-8 text-4xl bg-primary p-7 py-5 rounded-tl-xl rounded-br-xl"><%= card.value %></div>
    <img class="rounded-t-xl animate-fade-in block h-full w-full scale-100 transform opacity-100 transition duration-300 group-hover:scale-110" src="/images/love_letter/cards/<%= card.class.name.demodulize.downcase %>.webp" />
  </div>
  <div class="p-8 transition duration-300 ease-in-out group-hover:scale-105">
    <div class="text-2xl mb-3"><%= card.class.name.demodulize %></div>
    <div class="text-xs leading-5"><%= card.text %></div>
  </div>
</div>

app/views/love_letter/_player.html.erb
<div class="relative rounded-lg max-w-[200px]">
  <img class="rounded mr-4 w-[100px]" src=<%= "/images/love_letter/characters/#{player.metadata[:profile_picture]}" %> />
  <div class="absolute bottom-[5px] text-xs bg-primary px-2 py-0.5 text-white"><%= player.name %></div>
</div>

app/views/pages/index.html.erb
<div class="mt-28 mb-14 text-center">
  <h1 class="text-6xl text-primary">Love Letter</h1>
</div>
<div class="container flex flex-col items-center mx-auto px-5">
  <h2 class="font-bold mb-2 text-2xl">JOIN A GAME</h2>
  <%= form_with(url: play_path, method: :get, html: { class: "space-y-3" }) do |form| %>
    <div>
      <%= form.label :code, "Lobby Code" %>
      <%= form.text_field :code, autocomplete: "off", class: "form-control" %>
    </div>

    <div>
      <%= form.label :name, "Your Name" %>
      <%= form.text_field :name, autocomplete: "off", class: "form-control" %>
    </div>
    <%= form.submit "JOIN", class: "btn text-white btn-primary", name: nil %>
  <% end %>

  <h2 class="mt-10 mb-2 font-bold text-2xl">CREATE A LOBBY</h2>
  <%= form_with(model: Game.new, html: { class: "space-y-3" }) do |form| %>
    <div>
      <%= form.label :name, "Your Name", class: "form-control" %>
      <%= form.text_field :name, autocomplete: "off" %>
    </div>
    <%= form.button "JOIN", type: "submit", class: "btn text-white btn-primary", name: nil %>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="text-white text-center flex flex-row justify-center alert alert-warning notice rounded-none" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
    </svg>
    <p><%= sanitize notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="text-white text-center flex flex-row justify-center alert alert-error notice rounded-none" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
    </svg>
    <p><%= sanitize alert %></p>
  </div>
<% end %>